-- PROPOSED production schema; NOT used or applied by the public demo.
-- Authentication identities come from an established OIDC provider, never passwords here.
PRAGMA foreign_keys = ON;
CREATE TABLE users (id TEXT PRIMARY KEY, auth_subject TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE clients (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE memberships (tenant_id TEXT NOT NULL REFERENCES clients(id), user_id TEXT NOT NULL REFERENCES users(id), role TEXT NOT NULL CHECK(role IN ('client','admin')), PRIMARY KEY(tenant_id,user_id));
CREATE TABLE websites (id TEXT NOT NULL, tenant_id TEXT NOT NULL REFERENCES clients(id), name TEXT NOT NULL, domain TEXT NOT NULL, PRIMARY KEY(tenant_id,id));
CREATE TABLE provider_integrations (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES clients(id), provider TEXT NOT NULL, secret_reference TEXT NOT NULL, scope_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE health_snapshots (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, website_id TEXT NOT NULL, status TEXT NOT NULL, checked_at TEXT NOT NULL, metrics_json TEXT NOT NULL, provenance TEXT NOT NULL, FOREIGN KEY(tenant_id,website_id) REFERENCES websites(tenant_id,id));
CREATE TABLE traffic_summaries (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, website_id TEXT NOT NULL, period_start TEXT NOT NULL, period_end TEXT NOT NULL, summary_json TEXT NOT NULL, FOREIGN KEY(tenant_id,website_id) REFERENCES websites(tenant_id,id));
CREATE TABLE incidents (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, website_id TEXT NOT NULL, summary TEXT NOT NULL, detected_at TEXT NOT NULL, resolved_at TEXT, FOREIGN KEY(tenant_id,website_id) REFERENCES websites(tenant_id,id));
CREATE TABLE deployments (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, website_id TEXT NOT NULL, provider_reference TEXT NOT NULL, status TEXT NOT NULL, completed_at TEXT, FOREIGN KEY(tenant_id,website_id) REFERENCES websites(tenant_id,id));
CREATE TABLE backups (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, website_id TEXT NOT NULL, status TEXT NOT NULL, completed_at TEXT, storage_reference TEXT NOT NULL, FOREIGN KEY(tenant_id,website_id) REFERENCES websites(tenant_id,id));
CREATE TABLE announcements (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES clients(id), title TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE support_requests (id TEXT NOT NULL, tenant_id TEXT NOT NULL, website_id TEXT NOT NULL, created_by TEXT NOT NULL REFERENCES users(id), category TEXT NOT NULL, subject TEXT NOT NULL, description TEXT NOT NULL, affected_page TEXT NOT NULL, priority TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT, completion_summary TEXT, PRIMARY KEY(tenant_id,id), FOREIGN KEY(tenant_id,website_id) REFERENCES websites(tenant_id,id));
CREATE TABLE support_messages (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, request_id TEXT NOT NULL, author_id TEXT NOT NULL REFERENCES users(id), body TEXT NOT NULL, internal INTEGER NOT NULL DEFAULT 0 CHECK(internal IN (0,1)), created_at TEXT NOT NULL, FOREIGN KEY(tenant_id,request_id) REFERENCES support_requests(tenant_id,id));
CREATE TABLE attachments (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, request_id TEXT NOT NULL, object_key TEXT NOT NULL UNIQUE, filename TEXT NOT NULL, mime_type TEXT NOT NULL, byte_size INTEGER NOT NULL CHECK(byte_size BETWEEN 1 AND 5242880), scan_status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, FOREIGN KEY(tenant_id,request_id) REFERENCES support_requests(tenant_id,id));
CREATE TABLE estimates (id TEXT NOT NULL, tenant_id TEXT NOT NULL, request_id TEXT NOT NULL, revision INTEGER NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents>=0), currency TEXT NOT NULL DEFAULT 'USD', scope TEXT NOT NULL, approval_required INTEGER NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(tenant_id,id), UNIQUE(tenant_id,request_id,revision), FOREIGN KEY(tenant_id,request_id) REFERENCES support_requests(tenant_id,id));
CREATE TABLE approvals (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, estimate_id TEXT NOT NULL, actor_id TEXT NOT NULL REFERENCES users(id), decision TEXT NOT NULL CHECK(decision IN ('approved','declined')), decided_at TEXT NOT NULL, UNIQUE(tenant_id,estimate_id), FOREIGN KEY(tenant_id,estimate_id) REFERENCES estimates(tenant_id,id));
CREATE TABLE maintenance_plans (tenant_id TEXT PRIMARY KEY REFERENCES clients(id), plan_name TEXT NOT NULL, monthly_cents INTEGER NOT NULL, minutes_included INTEGER NOT NULL, minutes_used INTEGER NOT NULL, period_start TEXT NOT NULL, provider_reference TEXT);
CREATE TABLE audit_events (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES clients(id), actor_id TEXT NOT NULL REFERENCES users(id), action TEXT NOT NULL, entity_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX support_by_tenant ON support_requests(tenant_id,status,updated_at);
CREATE INDEX messages_by_request ON support_messages(tenant_id,request_id,created_at);
