"use client";
import {useEffect, useState} from "react";
const packages = [
{name:"Launch",price:750,description:"A focused first home for your business.",tag:"ONE PAGE / A CLEAR START",features:["1 page · up to 6 sections","Up to 15 supplied images","Services, hours & location","Call, WhatsApp or existing booking link","Basic page title & description","1 consolidated revision round"]},
{name:"Business",price:1250,description:"More room for your services and your story.",tag:"UP TO FIVE PAGES / MORE DEPTH",features:["Up to 5 pages & 30 supplied images","Service pages & gallery","Light editing of supplied copy","One simple contact form","Basic search indexing setup","2 consolidated revision rounds"]},
{name:"Appointments",price:1900,description:"A website connected to the way you book.",tag:"WEBSITE + BOOKING SETUP",features:["Everything in Business","One supported booking provider","Up to 10 services · 1 location","Up to 3 staff, subject to provider plan","Availability setup & test booking","60-minute owner training"]}
];
const carePlans=[{name:"No monthly care",price:0},{name:"Technical Care",price:49},{name:"Care Plus",price:99},{name:"Local Growth",price:199}];
const extras=[["Additional standard page","$150–$250"],["Spanish / English version","$250–$500"],["Business email setup","$100–$150"],["Google Business Profile assistance","$150–$250"],["Booking setup on an existing site","$200–$400"],["Seasonal landing page","$200–$350"],["Website refresh","From $300"]];
const questions=[
["What is included in every website?","Domain and hosting connection, HTTPS verification, mobile and keyboard checks, link testing, source handoff, and a 30-day correction period for defects in the agreed delivered scope. New features and third-party outages are outside that correction period."],
["Who owns the website and domain?","You own your domain and service accounts. After full payment, you receive the agreed website source, assets and handoff instructions. Your proposal explains rights to reusable components and third-party assets."],
["Are hosting, email and booking fees included?","Provider subscriptions are separate and paid directly by you. Basic static hosting can start at no cost within provider limits. Domain registration, email, paid booking plans and transaction fees are confirmed before you commit."],
["Do I have to subscribe to monthly care?","No. Monthly care is optional and begins at launch. If you end care, your paid-for website remains in your accounts while your provider services stay active. You arrange future updates and support separately."],
["What counts as a content update?","Changes to existing text, hours, prices or supplied images. New pages, redesigns, translations and integrations are quoted separately. Unused monthly time does not roll over. Additional approved work is $60/hour, with a 30-minute minimum."],
["How do payment and revisions work?","50% is due to begin, and 50% after preview approval before launch. Launch includes one consolidated revision round; Business and Appointments include two. The final proposal confirms scope, content requirements, timing and cancellation terms."],
["Can I add another language or an online store?","A Spanish/English version is an add-on, quoted to the page and word count. Online stores, custom applications and complex integrations need a separate scope. The website packages cover one language unless your proposal says otherwise."],
["When is support available?","Monday–Friday, 9 a.m.–5 p.m. Puerto Rico time. Routine requests are acknowledged within two business days; reported site-down issues within one business day. These are acknowledgement targets, not guaranteed resolution times or 24/7 coverage."]
];
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
export default function Home({assetBase = "/"}: {assetBase?: string} = {}){
 const [menuOpen,setMenuOpen]=useState(false);
 const [chosen,setChosen]=useState(0);
 const [care,setCare]=useState(0);
 const [business,setBusiness]=useState("");
 const [goal,setGoal]=useState("");
 const [notice,setNotice]=useState("");
 useEffect(()=>{if(!menuOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setMenuOpen(false);document.querySelector<HTMLButtonElement>(".menu-toggle")?.focus()}};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[menuOpen]);
 useEffect(()=>{const elements=document.querySelectorAll(".reveal"); if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return; const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("in-view");observer.unobserve(entry.target)}}),{threshold:0.08});elements.forEach(el=>{el.classList.add("will-reveal");observer.observe(el)});return()=>observer.disconnect()},[]);
 function selectPackage(index:number){setChosen(index);setNotice("");document.getElementById("project")?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});}
 function prepareBrief(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const text=["ADELVIO — WEBSITE PROJECT BRIEF","For Jose Rodriguez","jose.rodriguez.velez@gmail.com | (787) 413-3348","","Business: "+business,"Project: "+goal,"","Website: "+packages[chosen].name+" — "+money(packages[chosen].price)+" one-time","Optional care: "+carePlans[care].name+" — "+money(carePlans[care].price)+"/month","","50% to begin; 50% after preview approval before launch.","USD, before applicable taxes. Domain, email, hosting upgrades, booking subscriptions and transaction fees are separate.","This is a planning brief, not an accepted quote. Final scope and timing require agreement."].join("\n");const action=(event.nativeEvent as SubmitEvent).submitter?.getAttribute("data-action");if(action!=="download"){window.location.href="mailto:jose.rodriguez.velez@gmail.com?subject="+encodeURIComponent("Adelvio website inquiry — "+business)+"&body="+encodeURIComponent(text);setNotice("Your email app will open a draft. Review it and press Send there. If it does not open, download your brief and email Jose directly.");return;}const blob=new Blob([text],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="adelvio-project-brief.txt";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice("Your brief is ready to save. Nothing has been submitted.");}
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header wrap"><a className="wordmark" href="#" aria-label="Adelvio, home"><span className="brand-logo-frame"><img className="brand-logo" src={assetBase+"adelvio-logo.png"} alt="Adelvio" width={2048} height={768} decoding="async"/></span></a><nav className={menuOpen?"nav-open":""} aria-label="Main navigation"><a href="#approach" onClick={()=>setMenuOpen(false)}>The approach</a><a href="#packages" onClick={()=>setMenuOpen(false)}>Packages</a><a href="#care" onClick={()=>setMenuOpen(false)}>Ongoing care</a><a href="#about" onClick={()=>setMenuOpen(false)}>Meet Jose</a><a className="small-cta" href="#project" onClick={()=>setMenuOpen(false)}>Plan your website <span aria-hidden="true">↗</span></a></nav><button className="menu-toggle" aria-expanded={menuOpen} aria-controls="mobile-nav" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?"Close −":"Menu +"}</button>{menuOpen&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation"><a href="#approach" onClick={()=>setMenuOpen(false)}>The approach ↗</a><a href="#packages" onClick={()=>setMenuOpen(false)}>Packages ↗</a><a href="#care" onClick={()=>setMenuOpen(false)}>Ongoing care ↗</a><a href="#about" onClick={()=>setMenuOpen(false)}>Meet Jose ↗</a><a href="#project" onClick={()=>setMenuOpen(false)}>Plan your website ↗</a></nav>}</header><main id="main">
<section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span className="blue-dot"/> For small businesses in Puerto Rico</p><h1>Your business.<br/>A better first<br/><em>impression.</em></h1><p className="hero-description">Thoughtful websites that make your services clear, your business memorable, and the next step easy.</p><a className="button blue" href="#packages">Explore the packages <span>↗</span></a><p className="hero-note">A clear scope. Your own website. Care when you need it.</p></div><div className="hero-art" aria-label="Layered desktop and mobile concept website previews"><span className="art-label">A LITTLE PREVIEW OF THE POSSIBILITIES</span><div className="art-grid"/><div className="orbit">↗</div><div className="desktop-preview"><div className="browser-bar"><span>● ● ●</span><span>Website concept / 01</span><span>↗</span></div><div className="mini-nav"><b>DETAIL / STUDIO</b><span>Services &nbsp; About &nbsp; Contact ↗</span></div><div className="mini-body"><div><p className="mini-kicker">A DETAILING WEBSITE CONCEPT</p><h2>Care, in<br/>every detail.</h2><p>A considered space for your services.</p><span className="mini-button">Explore services ↗</span></div><div className="sculpture"><div className="sculpture-ring"/><span>01 / A NEW PERSPECTIVE</span></div></div><div className="mini-bottom"><span>Exterior care ↗</span><span>Interior care ↗</span><span>The finishing touch ↗</span></div></div><div className="phone-preview"><span className="phone-speaker"/><div className="phone-nav">DETAIL / <span>☰</span></div><span className="phone-label">YOUR NEXT STEP</span><h3>Good care.<br/>One tap away.</h3><div className="phone-graphic"><span>✳</span></div><div className="phone-row">Choose a service <span>⌄</span></div><div className="phone-row">Your vehicle <span>⌄</span></div><span className="phone-action">Request a quote ↗</span></div><div className="art-tag"><span>✳</span> Small screen.<br/>Same attention to detail.</div><p className="concept-caption">DESIGN CONCEPTS — NOT CLIENT WORK</p></div></section>
<div className="service-ribbon"><div className="wrap"><span>DESIGNED WITH INTENTION</span><span>Built for mobile <i>✳</i> Clear service packages <i>✳</i> Yours to keep</span><a href="#approach" aria-label="Explore the approach">↓</a></div></div>
<section className="approach wrap section-space" id="approach"><div className="section-heading reveal"><p className="eyebrow">01 / THE APPROACH</p><h2>Small business.<br/><span className="muted-heading">Big attention to detail.</span></h2></div><div className="approach-body reveal"><p className="lead">Your website should feel like your business at its best.</p><p>Make it easy for people to understand what you do, see your work, and take the next step. Start with the right-sized website, then choose the support that makes sense for you.</p><div className="principles"><div><span>01</span><h3>Designed around your services</h3><p>A clear structure, considered typography, and a straightforward path to contact or book.</p></div><div><span>02</span><h3>Clear scope. Clear ownership.</h3><p>Know what is included. Keep your domain, service accounts, and the agreed source files.</p></div><div><span>03</span><h3>Care that fits your needs</h3><p>Optional technical care, content updates, and improvements as your business evolves.</p></div></div></div></section>
<section className="showcase-section"><div className="wrap"><div className="showcase-top reveal"><p className="eyebrow">02 / DESIGN EXPLORATIONS</p><p>Different businesses.<br/>The same thoughtful approach.</p></div><div className="showcase-grid"><figure className="showcase reveal"><div className="concept-one" aria-label="Editorial services website design concept"><div className="showcase-browser"><span>● ● ●</span><span>CONCEPT / SERVICES</span><span>↗</span></div><div className="folio-nav"><b>THE DETAIL.</b><span>Good care starts here ↗</span></div><div className="folio-body"><div><span className="mini-kicker">A DIFFERENT PERSPECTIVE</span><h3>Made to<br/><em>stand out.</em></h3><span className="folio-button">Discover the details ↗</span></div><div className="folio-object"><div/><span>AN EXPLORATION IN FORM</span></div></div><div className="folio-foot"><span>Considered design.</span><span>From first look to next step.</span></div></div><figcaption><div><h3>An editorial first impression</h3><p>Service-led layout / Desktop concept</p></div><span>01 ↗</span></figcaption></figure><figure className="showcase showcase-offset reveal"><div className="concept-two" aria-label="Mobile booking website design concept"><span className="type-ghost" aria-hidden="true">Aa</span><div className="booking-phone"><div className="book-nav">YOUR NEXT CHAPTER <span>✳</span></div><p>A MOMENT FOR YOU</p><h3>A little time.<br/>Well spent.</h3><div className="book-art"><div/><span>↗</span></div><div className="book-service">Your next appointment <span>↗</span></div><div className="calendar-strip"><span>M<br/><b>12</b></span><span>T<br/><b>13</b></span><span className="chosen-date">W<br/><b>14</b></span><span>T<br/><b>15</b></span><span>F<br/><b>16</b></span></div><div className="book-submit">Explore availability ↗</div></div><span className="concept-two-note">SMALL SCREEN.<br/>THOUGHTFUL DETAILS.</span></div><figcaption><div><h3>A simpler next step</h3><p>Appointment-led layout / Mobile concept</p></div><span>02 ↗</span></figcaption></figure></div><p className="showcase-disclaimer">These are original design concepts, not completed client projects. No client outcomes are implied.</p></div></section>
<section className="packages-section wrap section-space" id="packages"><div className="split-heading reveal"><div><p className="eyebrow">03 / WEBSITE PACKAGES</p><h2>A good fit for<br/>your next chapter.</h2></div><p>One focused page or a little more room to grow. Choose a clear starting point for your business.</p></div><div className="package-grid">{packages.map((pack,index)=><article className="package reveal" key={pack.name}><div className="package-top"><span className="package-no">0{index+1}</span><span aria-hidden="true">↗</span></div><h3>{pack.name}</h3><p className="package-description">{pack.description}</p><p className="package-price">{money(pack.price)}<span>one-time build</span></p><p className="package-tag">{pack.tag}</p><ul>{pack.features.map(item=><li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul><button className={"button "+(index===1?"blue":"outline")} onClick={()=>selectPackage(index)}>Choose {pack.name}<span aria-hidden="true">↗</span></button></article>)}</div><div className="package-footnote"><p><b>Included in every build</b> Mobile layout, domain connection, HTTPS checks, testing, source handoff, and a 30-day correction period for delivered defects.</p><p>USD, before applicable taxes. One language unless agreed otherwise. Domain, email, hosting upgrades, booking subscriptions, and transaction fees are separate. 50% to begin; 50% before launch.</p></div></section>
<section className="process-section" id="process"><div className="wrap"><div className="process-title reveal"><div><p className="eyebrow">04 / HOW IT COMES TOGETHER</p><h2>Good work.<br/><span>Clear steps.</span></h2></div><p>A straightforward process, with space for your input and a clear moment to approve.</p></div><div className="process-grid">{[["Set the scope","Choose the pages, content and contact flow. Agree on the proposal and initial payment."],["Shape the website","Bring your approved text and images into a considered design. Review it together."],["Make it live","Approve the preview, complete the payment, and launch with tested links and a clear handoff."],["Choose your care","Keep things up to date with an optional plan, or manage future updates independently."]].map(([title,body],index)=><div className="process-step reveal" key={title}><span>0{index+1}</span><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>
<section className="care-section wrap section-space" id="care"><div className="split-heading reveal"><div><p className="eyebrow">05 / AFTER THE LAUNCH</p><h2>Keep it current.<br/><span className="muted-heading">Keep moving forward.</span></h2></div><p>Your website is yours. Ongoing care is optional, with clear limits and a plan for the work that matters.</p></div><div className="care-table reveal"><div className="care-row"><div><span className="care-index">01</span><h3>Technical Care</h3></div><p>Monitoring, monthly technical checks, recovery archive, renewal reminders. Up to 30 minutes of routine technical work.</p><p className="care-price">$49<span>/ month</span></p><a href="#project" onClick={()=>setCare(1)} aria-label="Select Technical Care">↗</a></div><div className="care-row"><div><span className="care-index">02</span><h3>Care Plus</h3></div><p>Technical Care, an inquiry-path check and work summary, plus up to 30 minutes of content edits.</p><p className="care-price">$99<span>/ month</span></p><a href="#project" onClick={()=>setCare(2)} aria-label="Select Care Plus">↗</a></div><div className="care-row"><div><span className="care-index">03</span><h3>Local Growth</h3></div><p>Technical coverage, monthly inquiry review, and up to 90 minutes for content updates and one prioritized improvement.</p><p className="care-price">$199<span>/ month</span></p><a href="#project" onClick={()=>setCare(3)} aria-label="Select Local Growth">↗</a></div></div><p className="fine-print">Care starts at launch. Unused time does not roll over. New pages, redesigns and integrations are separate. Additional approved work: $60/hour, 30-minute minimum.</p><div className="extras reveal"><div><p className="eyebrow">A LITTLE SOMETHING EXTRA</p><h3>Add what<br/>you need.</h3><p>Keep the first step focused.<br/>Build on it when the time is right.</p></div><dl>{extras.map(([title,price])=><div key={title}><dt>{title}</dt><dd>{price}</dd></div>)}</dl></div></section>
<section className="faq-section wrap section-space" id="questions"><div className="faq-heading reveal"><p className="eyebrow">06 / THE PRACTICAL DETAILS</p><h2>Good questions.<br/>Clear answers.</h2></div><div className="faq-list">{questions.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
<section className="founder-section wrap section-space" id="about"><figure className="founder-portrait reveal"><img src={assetBase+"profile_image.jpg"} alt="Jose Rodriguez, the person behind Adelvio" width={800} height={800} loading="lazy" decoding="async"/><figcaption>THE PERSON BEHIND ADELVIO <span aria-hidden="true">↗</span></figcaption></figure><div className="founder-copy reveal"><p className="eyebrow">PERSONAL ATTENTION / PUERTO RICO</p><h2>Hi, I’m Jose.<br/><span className="muted-heading">Let’s build your<br/>next chapter.</span></h2><p className="founder-intro">I’m Jose Rodriguez, the person behind Adelvio. I build websites for small businesses in Puerto Rico, with a focus on clear services, thoughtful design, and ongoing care.</p><p className="founder-degree">B.S. in Computer Engineering <span>PUPR</span></p><a className="founder-email" href="mailto:jose.rodriguez.velez@gmail.com">jose.rodriguez.velez@gmail.com <span aria-hidden="true">↗</span></a><a className="founder-phone" href="tel:+17874133348">(787) 413-3348 <span aria-hidden="true">↗</span></a><div className="social-links"><a href="https://www.linkedin.com/in/jose-g-rodriguez-velez/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://www.instagram.com/jose_rvelez/" target="_blank" rel="noopener noreferrer">Instagram ↗</a></div></div></section>
<section className="project-section" id="project"><div className="wrap project-layout"><div className="project-heading reveal"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Let's give your<br/>business a<br/><em>better hello.</em></h2><p>Tell me a little about your business. Choose a starting point and prepare an email to discuss your website.</p><div className="contact-shortcuts"><a href="mailto:jose.rodriguez.velez@gmail.com">Email Jose ↗</a><a href="tel:+17874133348">Call (787) 413-3348 ↗</a></div><span className="project-asterisk" aria-hidden="true">✳</span></div><form className="project-form" onSubmit={prepareBrief}><label htmlFor="business">Your business name<input id="business" autoComplete="organization" required maxLength={100} value={business} onChange={e=>setBusiness(e.target.value)} placeholder="The name behind the next chapter"/></label><div className="field-grid"><label htmlFor="build">Website package<select id="build" value={chosen} onChange={e=>{setChosen(Number(e.target.value));setNotice("")}}>{packages.map((p,i)=><option key={p.name} value={i}>{p.name} — {money(p.price)}</option>)}</select></label><label htmlFor="monthly">Optional ongoing care<select id="monthly" value={care} onChange={e=>{setCare(Number(e.target.value));setNotice("")}}>{carePlans.map((p,i)=><option key={p.name} value={i}>{p.name}{p.price?" — "+money(p.price)+"/mo":""}</option>)}</select></label></div><label htmlFor="goal">What would you like your website to do?<textarea id="goal" rows={3} required maxLength={1500} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Tell your story, show your services, make booking easier…"/></label><div className="brief-total" aria-live="polite"><span>YOUR STARTING POINT</span><div><strong>{money(packages[chosen].price)}</strong><span>build {care>0?"+ "+money(carePlans[care].price)+"/month care":"· no monthly care"}</span></div></div><p className="form-note">Before taxes and provider fees. Final scope and timing are confirmed in your proposal.</p><button className="button paper" type="submit" data-action="email">Prepare an email to Jose<span aria-hidden="true">↗</span></button><button className="brief-download" type="submit" data-action="download">Download your brief instead ↓</button><p className="download-note" role="status">{notice||"Opens your email app with a draft. You review and send it there."}</p></form></div></section>
</main><footer className="site-footer wrap"><a className="wordmark" href="#"><span className="brand-logo-frame"><img className="brand-logo" src={assetBase+"adelvio-logo.png"} alt="Adelvio" width={2048} height={768} decoding="async"/></span></a><span>By Jose Rodriguez · Websites for Puerto Rico’s small businesses.</span><a href="#main">Back to top ↑</a></footer></>;
}

